### PR TITLE
Added a filter menu with different image modification options

### PR DESCRIPTION
**Pull request by smeyerzab**
I added the following modifications that can be applied to all the images in a specified folder:
Change contrast
Change saturation
Change sharpness
Draw a black frame around inside border of image
Add a text as image watermark

I also added check for wrong user input and ways to navigate through the menus.

### CODE REVIEW

**Comment by alaudet** [comment]
Just ran this and it looks like this is applying the changes to the source folder now instead of destination (in linux).  I have picturea in ~/Pictures/in  and the output should go to ~/Pictures/out, not overwrite the 'in' folder.

I will also have to test it on Windows.  You added a lot of code so will take me a bit to go through it all, time is tight these days.  What I see looks pretty good though, you really took this further than I thought.

**Comment by smeyerzab** [comment]
Ok, that is true, the if statement that was checking for if the letter 's' was entered as out folder ('s' meaning use the same path for in and out) was wrong in that it returned true if the in folder path contained the letter 's' anywhere (such as in deSktop).
I changed it so that is needs the char s. So now it works.
I did another push, do I need to do another pull request?
Thanks again.

**Comment by alaudet** [comment]
I believe so yes.  Do another pull request and I will merge it into the devel branch.  Once we hammered away enough at it and everything is working exactly as we want on Windows and Linux I will merge into master.  

I think I would like to package it up to put on pypi as well.  So I can get that going.  Ideally all functionality will be in modules under the relish folder.  We can create scripts under bin to initiate the application.  

We can also get  some nosetests going so that if a change is made you just run it and make sure it works before copying it up.  A nosetest would of caught the outfolder right away.

I appreciate your interest, it's firing my imagination for other things I would like to add.

EDIT: forgot to mention, the next couple of weeks are tight for me, but I will most certainly work on this now after 8pm most nights.

**Comment by smeyerzab** [comment]
See if you see the changes, I am not sure there was a way to really do a new pull request of if this here gets updated.
Sounds good to do the packaging. You need to understand I am all new to this, so I am following your examples and guides on how to organize it properly. It sounds like the things I am interested in learning.
There are a few other things I also though of adding, but I wasn't sure how far you want to go with this. So we can brainstorm some.

I generally am a little tight on time, but I can put in an hour or two a day from work, more so next week.

**Comment by alaudet** [comment]
Ok will go take a look later.  Spending way too much time on this already today. :)
It's all good.  Contribute what you like, I am an amateur as well.

I think you just make your changes, upload them to your forked repo and issue another pull.

Make sure to update your forked repo as well in case I make some updates.  I will add all my updates in the devel branch.  Master will be for releases.

**Comment by smeyerzab** [comment]
I think i then close this pull request, as this is in the master branch, and we can move to the development branch.

**Pull request closed without merging**
